version: "3.7"

services:
  rabbitmq-master:
    build: .
    restart: always
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
      - ${RABBITMQ_MASTER_PORT}:5672
    networks:
      - default

networks:
  default:
