version: "3.7"

services:
  rabbitmq-master:
    image: rabbitmq:3-management
    restart: always
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
      - ${RABBITMQ_MASTER_PORT}:5672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - default

volumes:
  rabbitmq:

networks:
  default:
